# Generated by Django 3.1.4 on 2021-01-11 17:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('abbr', models.CharField(max_length=10)),
                ('date_created', models.DateField(auto_now=True)),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='correspondence.office')),
            ],
        ),
        migrations.CreateModel(
            name='Radicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField(max_length=30)),
                ('subject', models.TextField(max_length=256, null=True)),
                ('type', models.TextField(choices=[('EN', 'Entrada'), ('SA', 'Salida'), ('ME', 'Memorando')], default='EN', max_length=60)),
                ('date_radicated', models.DateField(default=datetime.datetime.now)),
                ('reception_mode', models.TextField(choices=[('VA', 'Valija'), ('EL', 'Electrónico'), ('472', '472'), ('PR', 'Presencial')], default='PR', max_length=10)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='correspondence.office')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.TextField(choices=[('CC', 'Cédula de ciudadanía'), ('NIT', 'Número único de identificación tributaria'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cédula de extranjería')], max_length=60, null=True)),
                ('document_number', models.CharField(max_length=25, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('city', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='correspondence.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='correspondence.state'),
        ),
    ]
