# Generated by Django 3.1.4 on 2021-01-11 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radicate',
            name='person',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='radicates', to='correspondence.person'),
        ),
    ]
