# Generated by Django 3.1.4 on 2021-01-13 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0002_radicate_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicate',
            name='date_radicated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
