# Generated by Django 3.1.4 on 2021-01-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0004_auto_20210119_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicate',
            name='document_file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
