# Generated by Django 3.1.4 on 2021-01-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0005_auto_20210120_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='radicate',
            name='cmis_id',
            field=models.TextField(max_length=128, null=True),
        ),
    ]
