# Generated by Django 3.1.4 on 2021-01-27 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0009_auto_20210127_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicate',
            name='actual_user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='radicates_user', to='correspondence.person'),
        ),
    ]
