# Generated by Django 3.1.4 on 2021-01-27 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0011_auto_20210127_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radicate',
            old_name='actual_user',
            new_name='current_user',
        ),
    ]
