# Generated by Django 3.1.4 on 2021-01-29 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0012_auto_20210127_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='correspondence.person'),
        ),
    ]
